# Usa a imagem base do Debian
FROM debian:latest

# Atualiza o sistema e instala o Python
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

# Define o diretório de trabalho
WORKDIR /app

# Copia o conteúdo da pasta local para o contêiner
COPY ../* /app

